import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { bytesToHex, hexToBytes } from "@noble/hashes/utils.js";
import { Writer } from "../src/proto.js";
import { Key, buildSend, memoOf, parseAmount, formatAeth, signingMessage, DIRECTORY_ADDRESS, transfers, isAddress } from "../src/index.js";

// Byte-for-byte agreement with the chain's Go implementation
// (clients/testdata/vectors.json, generated by go test ./clients/vectors).
const v = JSON.parse(readFileSync(new URL("../../../testdata/vectors.json", import.meta.url), "utf8"));

test("mnemonic derives the same key and address as the Go wallet", () => {
  const key = Key.fromMnemonic(v.key.mnemonic);
  assert.equal(bytesToHex(key.seed), v.key.seed);
  assert.equal(bytesToHex(key.publicKey), v.key.pubKey);
  assert.equal(key.address, v.key.address);
});

test("signatures interoperate with Go", () => {
  const key = Key.fromMnemonic(v.key.mnemonic);
  const msg = hexToBytes(v.signature.message);
  assert.ok(Key.verify(key.publicKey, msg, hexToBytes(v.signature.signature)), "verifies Go's signature");
  assert.equal(bytesToHex(key.sign(msg, { deterministic: true })), v.signature.signature, "deterministic signature is identical");
  const mine = key.sign(msg);
  assert.ok(Key.verify(key.publicKey, msg, mine));
  assert.ok(!Key.verify(key.publicKey, new TextEncoder().encode("other"), mine), "a signature covers exactly its message");
});

test("signed transactions are byte-identical to the Go wallet's", () => {
  const key = Key.fromMnemonic(v.key.mnemonic);
  for (const t of v.txs) {
    const s = buildSend(key, { chainId: t.chainId, accountNumber: BigInt(t.accountNumber), sequence: BigInt(t.sequence), to: t.to, amountUaeth: BigInt(t.amountUaeth), memo: t.memo, gasLimit: BigInt(t.gasLimit) }, { deterministic: true });
    assert.equal(bytesToHex(s.bodyBytes), t.bodyBytes, "body");
    assert.equal(bytesToHex(s.authInfoBytes), t.authInfoBytes, "auth info");
    assert.equal(bytesToHex(s.signDoc), t.signDoc, "sign doc");
    assert.equal(bytesToHex(s.signature), t.signature, "signature");
    assert.equal(bytesToHex(s.txBytes), t.txBytes, "tx bytes");
    assert.equal(s.hash, t.txHash, "tx hash");
    assert.equal(memoOf(hexToBytes(t.txBytes)), t.memo);
  }
});

test("prepaid request signing message matches the Go seller", () => {
  const p = v.prepaid;
  const msg = signingMessage({ network: p.Network, payTo: p.PayTo, host: p.Host, method: p.Method, path: p.Path, body: new TextEncoder().encode(p.body), maxPrice: BigInt(p.maxPrice), timestamp: p.timestamp, requestId: p.RequestID, depositTx: p.DepositTx });
  assert.equal(bytesToHex(msg), p.message);
});

test("query encodings and the directory address match", () => {
  assert.equal(bytesToHex(new Writer().string(1, v.key.address).finish()), v.queries.accountInfoRequest);
  assert.equal(bytesToHex(new Writer().string(1, v.key.address).string(2, "uaeth").finish()), v.queries.balanceRequest);
  assert.equal(DIRECTORY_ADDRESS, v.directoryAddress);
});

test("amounts need a unit and are parsed strictly", () => {
  assert.equal(parseAmount("1.5 AETH"), 1_500_000n);
  assert.equal(parseAmount("0100000uaeth"), 100_000n, "base 10, never octal");
  assert.equal(parseAmount("0.000001 aeth"), 1n);
  for (const bad of ["1500000", "1.0000001 AETH", "1.5 uaeth", "0 AETH", "1 BTC", "-1 AETH"]) assert.throws(() => parseAmount(bad), bad);
  assert.equal(formatAeth(1_500_000n), "1.5");
  assert.equal(formatAeth(1n), "0.000001");
});

test("addresses are checked", () => {
  assert.ok(isAddress(v.key.address));
  assert.ok(!isAddress(v.key.address.slice(0, -1) + (v.key.address.endsWith("q") ? "p" : "q")), "a typo fails the checksum");
  assert.ok(!isAddress("cosmos1qyqszqgpqyqszqgpqyqszqgpqyqszqgpjnp7du"));
  const key = Key.fromMnemonic(v.key.mnemonic);
  assert.throws(() => buildSend(key, { chainId: "x", accountNumber: 0, sequence: 0, to: "aether1bogus", amountUaeth: 1n }));
});

test("transfers are read from events", () => {
  const t = transfers([
    { type: "coin_spent", attributes: [] },
    { type: "transfer", attributes: [{ key: "recipient", value: "B" }, { key: "sender", value: "A" }, { key: "amount", value: "150uaeth" }] },
  ]);
  assert.deepEqual(t, [{ from: "A", to: "B", amountUaeth: 150n }]);
});

test("a recovery phrase is validated", () => {
  assert.throws(() => Key.fromMnemonic(v.key.mnemonic.replace(/art$/, "zoo")));
  const { key, mnemonic } = Key.generate();
  assert.equal(mnemonic.split(" ").length, 24);
  assert.equal(Key.fromMnemonic(mnemonic).address, key.address);
});
