// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aether/escrow/v1/escrow.proto

package escrow

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// OnExpiry is what happens to an escrow nobody settled by its deadline.
type OnExpiry int32

const (
	ON_EXPIRY_UNSPECIFIED OnExpiry = 0
	// Back to the payer: protects the payer; the payee's recourse is the arbiter.
	ON_EXPIRY_REFUND OnExpiry = 1
	// On to the payee: protects the payee; the payer's recourse is the arbiter.
	ON_EXPIRY_RELEASE OnExpiry = 2
)

var OnExpiry_name = map[int32]string{
	0: "ON_EXPIRY_UNSPECIFIED",
	1: "ON_EXPIRY_REFUND",
	2: "ON_EXPIRY_RELEASE",
}

var OnExpiry_value = map[string]int32{
	"ON_EXPIRY_UNSPECIFIED": 0,
	"ON_EXPIRY_REFUND":      1,
	"ON_EXPIRY_RELEASE":     2,
}

func (x OnExpiry) String() string {
	return proto.EnumName(OnExpiry_name, int32(x))
}

func (OnExpiry) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_58bba3811373c1a4, []int{0}
}

// Escrow is money a payer has locked for a payee until one of them, or
// the arbiter, settles it, or it expires. Settled escrows are deleted;
// their outcome stays in the escrow_released / escrow_refunded events.
type Escrow struct {
	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Payer string `protobuf:"bytes,2,opt,name=payer,proto3" json:"payer,omitempty"`
	Payee string `protobuf:"bytes,3,opt,name=payee,proto3" json:"payee,omitempty"`
	// Optional: may release or refund at any time.
	Arbiter string                                   `protobuf:"bytes,4,opt,name=arbiter,proto3" json:"arbiter,omitempty"`
	Amount  github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
	// Unix seconds, compared with block time.
	ExpiresAt int64    `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	OnExpiry  OnExpiry `protobuf:"varint,7,opt,name=on_expiry,json=onExpiry,proto3,enum=aether.escrow.v1.OnExpiry" json:"on_expiry,omitempty"`
	// What the money is for, e.g. "invoice #42" or a hash of the job spec.
	Terms         string `protobuf:"bytes,8,opt,name=terms,proto3" json:"terms,omitempty"`
	CreatedHeight int64  `protobuf:"varint,9,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
}

func (m *Escrow) Reset()         { *m = Escrow{} }
func (m *Escrow) String() string { return proto.CompactTextString(m) }
func (*Escrow) ProtoMessage()    {}
func (*Escrow) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bba3811373c1a4, []int{0}
}
func (m *Escrow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Escrow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Escrow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Escrow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Escrow.Merge(m, src)
}
func (m *Escrow) XXX_Size() int {
	return m.Size()
}
func (m *Escrow) XXX_DiscardUnknown() {
	xxx_messageInfo_Escrow.DiscardUnknown(m)
}

var xxx_messageInfo_Escrow proto.InternalMessageInfo

func (m *Escrow) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Escrow) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *Escrow) GetPayee() string {
	if m != nil {
		return m.Payee
	}
	return ""
}

func (m *Escrow) GetArbiter() string {
	if m != nil {
		return m.Arbiter
	}
	return ""
}

func (m *Escrow) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Escrow) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *Escrow) GetOnExpiry() OnExpiry {
	if m != nil {
		return m.OnExpiry
	}
	return ON_EXPIRY_UNSPECIFIED
}

func (m *Escrow) GetTerms() string {
	if m != nil {
		return m.Terms
	}
	return ""
}

func (m *Escrow) GetCreatedHeight() int64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

type GenesisState struct {
	NextId  uint64   `protobuf:"varint,1,opt,name=next_id,json=nextId,proto3" json:"next_id,omitempty"`
	Escrows []Escrow `protobuf:"bytes,2,rep,name=escrows,proto3" json:"escrows"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_58bba3811373c1a4, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetNextId() uint64 {
	if m != nil {
		return m.NextId
	}
	return 0
}

func (m *GenesisState) GetEscrows() []Escrow {
	if m != nil {
		return m.Escrows
	}
	return nil
}

func init() {
	proto.RegisterEnum("aether.escrow.v1.OnExpiry", OnExpiry_name, OnExpiry_value)
	proto.RegisterType((*Escrow)(nil), "aether.escrow.v1.Escrow")
	proto.RegisterType((*GenesisState)(nil), "aether.escrow.v1.GenesisState")
}

func init() { proto.RegisterFile("aether/escrow/v1/escrow.proto", fileDescriptor_58bba3811373c1a4) }

var fileDescriptor_58bba3811373c1a4 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x6d, 0x27, 0xcd, 0x9f, 0x05, 0xa2, 0xb0, 0x4a, 0xc5, 0x36, 0x52, 0xdd, 0xa8, 0x12,
	0xc2, 0x42, 0xc2, 0x26, 0xe5, 0x00, 0xd7, 0xa4, 0x75, 0x21, 0x12, 0x4a, 0x2b, 0x47, 0x95, 0x0a,
	0x17, 0x6b, 0x63, 0x8f, 0xe2, 0x05, 0xc5, 0x1b, 0x79, 0x37, 0x69, 0xf2, 0x06, 0x1c, 0x79, 0x07,
	0x6e, 0x3c, 0x49, 0x8f, 0x3d, 0xf6, 0x04, 0x28, 0x79, 0x11, 0xe4, 0xf5, 0x86, 0x56, 0xf4, 0xe4,
	0xf9, 0x7e, 0x33, 0xde, 0xfd, 0x76, 0x66, 0xd0, 0x3e, 0x05, 0x99, 0x40, 0xe6, 0x81, 0x88, 0x32,
	0x7e, 0xe5, 0x2d, 0xba, 0x3a, 0x72, 0x67, 0x19, 0x97, 0x1c, 0x37, 0x8b, 0xb4, 0xab, 0xe1, 0xa2,
	0xdb, 0x6e, 0x4d, 0xf8, 0x84, 0xab, 0xa4, 0x97, 0x47, 0x45, 0x5d, 0xdb, 0x8e, 0xb8, 0x98, 0x72,
	0xe1, 0x8d, 0xa9, 0x00, 0x6f, 0xd1, 0x1d, 0x83, 0xa4, 0x5d, 0x2f, 0xe2, 0x2c, 0x2d, 0xf2, 0x87,
	0xb7, 0x16, 0xaa, 0xf8, 0xea, 0x0c, 0xdc, 0x40, 0x16, 0x8b, 0x89, 0xd9, 0x31, 0x9d, 0x72, 0x60,
	0xb1, 0x18, 0xb7, 0xd0, 0xce, 0x8c, 0xae, 0x20, 0x23, 0x56, 0xc7, 0x74, 0xea, 0x41, 0x21, 0xb6,
	0x14, 0x48, 0xe9, 0x8e, 0x02, 0x26, 0xa8, 0x4a, 0xb3, 0x31, 0x93, 0x90, 0x91, 0xb2, 0xe2, 0x5b,
	0x89, 0x23, 0x54, 0xa1, 0x53, 0x3e, 0x4f, 0x25, 0xd9, 0xe9, 0x94, 0x9c, 0x47, 0x47, 0x7b, 0x6e,
	0xe1, 0xc8, 0xcd, 0x1d, 0xb9, 0xda, 0x91, 0x7b, 0xcc, 0x59, 0xda, 0x7f, 0x7d, 0xfd, 0xeb, 0xc0,
	0xf8, 0xf9, 0xfb, 0xc0, 0x99, 0x30, 0x99, 0xcc, 0xc7, 0x6e, 0xc4, 0xa7, 0x9e, 0xb6, 0x5f, 0x7c,
	0x5e, 0x89, 0xf8, 0xab, 0x27, 0x57, 0x33, 0x10, 0xea, 0x07, 0x11, 0xe8, 0xa3, 0xf1, 0x3e, 0x42,
	0xb0, 0x9c, 0xb1, 0x0c, 0x44, 0x48, 0x25, 0xa9, 0x74, 0x4c, 0xa7, 0x14, 0xd4, 0x35, 0xe9, 0x49,
	0xfc, 0x16, 0xd5, 0x79, 0x1a, 0x2a, 0xbd, 0x22, 0xd5, 0x8e, 0xe9, 0x34, 0x8e, 0xda, 0xee, 0xff,
	0x0d, 0x74, 0xcf, 0x52, 0x5f, 0x55, 0x04, 0x35, 0xae, 0xa3, 0xfc, 0xb1, 0x12, 0xb2, 0xa9, 0x20,
	0xb5, 0xe2, 0xb1, 0x4a, 0xe0, 0xe7, 0xa8, 0x11, 0x65, 0x40, 0x25, 0xc4, 0x61, 0x02, 0x6c, 0x92,
	0x48, 0x52, 0x57, 0x37, 0x3e, 0xd1, 0xf4, 0x83, 0x82, 0x87, 0x14, 0x3d, 0x7e, 0x0f, 0x29, 0x08,
	0x26, 0x46, 0x92, 0x4a, 0xc0, 0xcf, 0x50, 0x35, 0x85, 0xa5, 0x0c, 0xff, 0x35, 0xb9, 0x92, 0xcb,
	0x41, 0x8c, 0xdf, 0xa1, 0x6a, 0xe1, 0x42, 0x10, 0x4b, 0xf5, 0x88, 0x3c, 0x34, 0x57, 0xcc, 0xa8,
	0x5f, 0xce, 0x5b, 0x14, 0x6c, 0xcb, 0x5f, 0x5e, 0xa2, 0xda, 0xd6, 0x35, 0xde, 0x43, 0xbb, 0x67,
	0xc3, 0xd0, 0xbf, 0x3c, 0x1f, 0x04, 0x9f, 0xc2, 0x8b, 0xe1, 0xe8, 0xdc, 0x3f, 0x1e, 0x9c, 0x0e,
	0xfc, 0x93, 0xa6, 0x81, 0x5b, 0xa8, 0x79, 0x97, 0x0a, 0xfc, 0xd3, 0x8b, 0xe1, 0x49, 0xd3, 0xc4,
	0xbb, 0xe8, 0xe9, 0x7d, 0xfa, 0xd1, 0xef, 0x8d, 0xfc, 0xa6, 0xd5, 0x2e, 0x7f, 0xfb, 0x61, 0x1b,
	0xfd, 0xde, 0xf5, 0xda, 0x36, 0x6f, 0xd6, 0xb6, 0xf9, 0x67, 0x6d, 0x9b, 0xdf, 0x37, 0xb6, 0x71,
	0xb3, 0xb1, 0x8d, 0xdb, 0x8d, 0x6d, 0x7c, 0x7e, 0x71, 0x6f, 0x3a, 0x57, 0x09, 0x5f, 0xf1, 0xf9,
	0x17, 0x2e, 0x12, 0x96, 0x7a, 0x7a, 0x61, 0x97, 0x7a, 0x51, 0xc7, 0x15, 0xb5, 0x61, 0x6f, 0xfe,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x83, 0xfa, 0xe2, 0x42, 0xca, 0x02, 0x00, 0x00,
}

func (m *Escrow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Escrow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Escrow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedHeight != 0 {
		i = encodeVarintEscrow(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Terms) > 0 {
		i -= len(m.Terms)
		copy(dAtA[i:], m.Terms)
		i = encodeVarintEscrow(dAtA, i, uint64(len(m.Terms)))
		i--
		dAtA[i] = 0x42
	}
	if m.OnExpiry != 0 {
		i = encodeVarintEscrow(dAtA, i, uint64(m.OnExpiry))
		i--
		dAtA[i] = 0x38
	}
	if m.ExpiresAt != 0 {
		i = encodeVarintEscrow(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEscrow(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Arbiter) > 0 {
		i -= len(m.Arbiter)
		copy(dAtA[i:], m.Arbiter)
		i = encodeVarintEscrow(dAtA, i, uint64(len(m.Arbiter)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Payee) > 0 {
		i -= len(m.Payee)
		copy(dAtA[i:], m.Payee)
		i = encodeVarintEscrow(dAtA, i, uint64(len(m.Payee)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Payer) > 0 {
		i -= len(m.Payer)
		copy(dAtA[i:], m.Payer)
		i = encodeVarintEscrow(dAtA, i, uint64(len(m.Payer)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintEscrow(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Escrows) > 0 {
		for iNdEx := len(m.Escrows) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Escrows[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEscrow(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.NextId != 0 {
		i = encodeVarintEscrow(dAtA, i, uint64(m.NextId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEscrow(dAtA []byte, offset int, v uint64) int {
	offset -= sovEscrow(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Escrow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovEscrow(uint64(m.Id))
	}
	l = len(m.Payer)
	if l > 0 {
		n += 1 + l + sovEscrow(uint64(l))
	}
	l = len(m.Payee)
	if l > 0 {
		n += 1 + l + sovEscrow(uint64(l))
	}
	l = len(m.Arbiter)
	if l > 0 {
		n += 1 + l + sovEscrow(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovEscrow(uint64(l))
		}
	}
	if m.ExpiresAt != 0 {
		n += 1 + sovEscrow(uint64(m.ExpiresAt))
	}
	if m.OnExpiry != 0 {
		n += 1 + sovEscrow(uint64(m.OnExpiry))
	}
	l = len(m.Terms)
	if l > 0 {
		n += 1 + l + sovEscrow(uint64(l))
	}
	if m.CreatedHeight != 0 {
		n += 1 + sovEscrow(uint64(m.CreatedHeight))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NextId != 0 {
		n += 1 + sovEscrow(uint64(m.NextId))
	}
	if len(m.Escrows) > 0 {
		for _, e := range m.Escrows {
			l = e.Size()
			n += 1 + l + sovEscrow(uint64(l))
		}
	}
	return n
}

func sovEscrow(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEscrow(x uint64) (n int) {
	return sovEscrow(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Escrow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEscrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Escrow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Escrow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Arbiter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Arbiter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEscrow
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnExpiry", wireType)
			}
			m.OnExpiry = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OnExpiry |= OnExpiry(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Terms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Terms = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEscrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEscrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEscrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextId", wireType)
			}
			m.NextId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Escrows", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEscrow
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Escrows = append(m.Escrows, Escrow{})
			if err := m.Escrows[len(m.Escrows)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEscrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEscrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEscrow(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEscrow
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEscrow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEscrow
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEscrow
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEscrow
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEscrow        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEscrow          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEscrow = fmt.Errorf("proto: unexpected end of group")
)
