#!/usr/bin/env bash
# The "pay another agent for a tool call with a spend-capped grant" demo:
# a real seller (cmd/paywall, offering aether-pull) and a real buyer
# (cmd/agentmcp, driven exactly as an MCP client would drive it) transact
# for real AETH on the public testnet. Two fresh, disposable keypairs; no
# funds beyond a couple of faucet drips. Run it from a checkout of this repo:
#
#   bash scripts/demo-agent-payment.sh
#
# Writes a full JSON transcript and a human-readable write-up to OUT_DIR
# (default ./demo-out), including every tx hash and its explorer link.
# It's read by anyone deciding whether this is real: every number in it
# is checked against the chain, not just echoed from what a tool claimed.
#
# Override with environment variables for a different network:
#   RPC GRPC FAUCET CHAIN_ID EXPLORER ALLOWANCE OUT_DIR
set -euo pipefail

RPC=${RPC:-http://157.245.252.221:26657}
GRPC=${GRPC:-157.245.252.221:9090}
FAUCET=${FAUCET:-http://157.245.252.221:8080/request}
CHAIN_ID=${CHAIN_ID:-aether-testnet-1}
EXPLORER=${EXPLORER:-http://157.245.252.221:8081}
ALLOWANCE=${ALLOWANCE:-0.01 AETH}
OUT_DIR=${OUT_DIR:-./demo-out}

ROOT=$(cd "$(dirname "$0")/.." && pwd)
WORK=$(mktemp -d)
trap 'kill $(jobs -p) 2>/dev/null; rm -rf "$WORK"' EXIT
mkdir -p "$OUT_DIR"

echo "==> building aetherd, paywall, agentmcp"
go build -o "$WORK/aetherd" "$ROOT/cmd/aetherd"
go build -o "$WORK/paywall" "$ROOT/cmd/paywall"
go build -o "$WORK/agentmcp" "$ROOT/cmd/agentmcp"
A="$WORK/aetherd --home $WORK/sellerhome"

echo "==> creating the seller's payee and collector keys"
$A keys add sellerpayee --keyring-backend test >/dev/null 2>&1
$A keys add collector --keyring-backend test >/dev/null 2>&1
SELLER=$($A keys show sellerpayee -a --keyring-backend test)
COLLECTOR=$($A keys show collector -a --keyring-backend test)
echo "    seller  = $SELLER"
echo "    collector = $COLLECTOR"

fund() { # address
  curl -sS -X POST "$FAUCET" -H 'Content-Type: application/json' -d "{\"address\":\"$1\"}" || true
  echo
}
echo "==> funding the seller and collector from the faucet"
fund "$SELLER"
fund "$COLLECTOR"
sleep 5

UPSTREAM_PORT=38999
PAYWALL_PORT=38402
python3 "$ROOT/scripts/demo_upstream.py" 127.0.0.1 $UPSTREAM_PORT &
sleep 1

echo "==> starting the seller: cmd/paywall offering aether-pull"
"$WORK/paywall" \
  --listen ":$PAYWALL_PORT" \
  --upstream "http://127.0.0.1:$UPSTREAM_PORT/fact" \
  --pay-to "$SELLER" \
  --price "0.001 AETH" \
  --grpc "$GRPC" \
  --chain-id "$CHAIN_ID" \
  --pull-key collector \
  --pull-ledger "$WORK/ledger.json" \
  --pull-credit "$ALLOWANCE" \
  --pull-collect-every 10s \
  --keyring-dir "$WORK/sellerhome" --keyring-backend test \
  --name "Fun Fact API (demo)" --description "A random fun fact per request -- scripts/demo-agent-payment.sh" \
  > "$OUT_DIR/paywall.log" 2>&1 &
sleep 2

echo "==> running the buyer: cmd/agentmcp, driven as an MCP client would"
DRIVER_OUT=$(python3 "$ROOT/scripts/demo_agent_payment.py" \
  "http://127.0.0.1:$PAYWALL_PORT/fact" "$ALLOWANCE" "$OUT_DIR/transcript.json" -- \
  "$WORK/agentmcp" --grpc "$GRPC" --rpc "$RPC" --chain-id "$CHAIN_ID" --faucet "$FAUCET" \
  --keyring-dir "$WORK/buyerhome" --per-tx-limit 1000000 --daily-limit 5000000 \
  2> >(tee "$OUT_DIR/agentmcp-driver.log" >&2))
BUYER=$(python3 -c "import json,sys; print(json.load(sys.stdin)['address'])" <<<"$DRIVER_OUT")
echo "    buyer = $BUYER"

echo "==> waiting for the seller to collect what's owed"
sleep 15

echo "==> verifying on chain (not just trusting what the tools reported)"
node_bal() { $A query bank balances "$1" --node "$RPC" -o json | python3 -c "import json,sys; b=json.load(sys.stdin)['balances']; print(next((c['amount'] for c in b if c['denom']=='uaeth'), '0'))"; }
SELLER_BAL=$(node_bal "$SELLER")
COLLECTION_TX=$(python3 -c "
import json
c = json.load(open('$WORK/ledger.json'))['collections']
print(next(iter(c.values()))['txHash'])
")

cat > "$OUT_DIR/README.md" <<EOF
# Bot-to-bot payment, live on $CHAIN_ID

Generated by \`scripts/demo-agent-payment.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).

Two fresh, disposable keypairs, never used before this run:

- **Buyer** (\`cmd/agentmcp\`, driven exactly as an MCP client would): \`$BUYER\`
- **Seller payee** (\`cmd/paywall\`, offering \`aether-pull\`): \`$SELLER\`
- **Seller's collector** (the account the buyer's grant pays): \`$COLLECTOR\`

## What happened

1. The buyer's agent asked the testnet faucet to fund itself.
2. It called \`fetch_paid\` on a paid "fun fact" API three times, each under \`maxAmount\`. The first call
   found the service offers \`aether-pull\` and granted the collector a **$ALLOWANCE** allowance, payable
   only to the seller, for 7 days, revocable at any time -- **one on-chain transaction**. Every call after
   that settled **instantly by signature**, no block wait.
3. The seller's collector batched what was owed into **one** \`MsgExec\`, spending under that grant.
4. The seller's balance increased by exactly what was owed. Verified against the chain, not just the
   paywall's own bookkeeping: **$SELLER_BAL uaeth**.

## Check it yourself

- Buyer: $EXPLORER/address/$BUYER
- Seller: $EXPLORER/address/$SELLER
- Collector: $EXPLORER/address/$COLLECTOR
- The collection transaction (\`MsgExec\`): $EXPLORER/tx/$COLLECTION_TX

The full MCP tool-call transcript (every request and response, including the seller's signed receipts)
is in \`transcript.json\` next to this file.
EOF

echo
echo "==> done. Write-up: $OUT_DIR/README.md"
cat "$OUT_DIR/README.md"
