// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aether/pow/v1/tx.proto

package pow

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterValidatorPubkey struct {
	Miner           string `protobuf:"bytes,1,opt,name=miner,proto3" json:"miner,omitempty"`
	ConsensusPubkey []byte `protobuf:"bytes,2,opt,name=consensus_pubkey,json=consensusPubkey,proto3" json:"consensus_pubkey,omitempty"`
	Signature       []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *MsgRegisterValidatorPubkey) Reset()         { *m = MsgRegisterValidatorPubkey{} }
func (m *MsgRegisterValidatorPubkey) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterValidatorPubkey) ProtoMessage()    {}
func (*MsgRegisterValidatorPubkey) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eb53289cba3cd1f, []int{0}
}
func (m *MsgRegisterValidatorPubkey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterValidatorPubkey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterValidatorPubkey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterValidatorPubkey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterValidatorPubkey.Merge(m, src)
}
func (m *MsgRegisterValidatorPubkey) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterValidatorPubkey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterValidatorPubkey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterValidatorPubkey proto.InternalMessageInfo

func (m *MsgRegisterValidatorPubkey) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *MsgRegisterValidatorPubkey) GetConsensusPubkey() []byte {
	if m != nil {
		return m.ConsensusPubkey
	}
	return nil
}

func (m *MsgRegisterValidatorPubkey) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type MsgRegisterValidatorPubkeyResponse struct {
}

func (m *MsgRegisterValidatorPubkeyResponse) Reset()         { *m = MsgRegisterValidatorPubkeyResponse{} }
func (m *MsgRegisterValidatorPubkeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterValidatorPubkeyResponse) ProtoMessage()    {}
func (*MsgRegisterValidatorPubkeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eb53289cba3cd1f, []int{1}
}
func (m *MsgRegisterValidatorPubkeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterValidatorPubkeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterValidatorPubkeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterValidatorPubkeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterValidatorPubkeyResponse.Merge(m, src)
}
func (m *MsgRegisterValidatorPubkeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterValidatorPubkeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterValidatorPubkeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterValidatorPubkeyResponse proto.InternalMessageInfo

type MsgSubmitPoW struct {
	Miner      string `protobuf:"bytes,1,opt,name=miner,proto3" json:"miner,omitempty"`
	Height     uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp  int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PrevHash   []byte `protobuf:"bytes,4,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	MerkleRoot []byte `protobuf:"bytes,5,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	Nonce      uint64 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Difficulty uint64 `protobuf:"varint,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
}

func (m *MsgSubmitPoW) Reset()         { *m = MsgSubmitPoW{} }
func (m *MsgSubmitPoW) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitPoW) ProtoMessage()    {}
func (*MsgSubmitPoW) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eb53289cba3cd1f, []int{2}
}
func (m *MsgSubmitPoW) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitPoW) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitPoW.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitPoW) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitPoW.Merge(m, src)
}
func (m *MsgSubmitPoW) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitPoW) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitPoW.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitPoW proto.InternalMessageInfo

func (m *MsgSubmitPoW) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *MsgSubmitPoW) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *MsgSubmitPoW) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MsgSubmitPoW) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *MsgSubmitPoW) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *MsgSubmitPoW) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MsgSubmitPoW) GetDifficulty() uint64 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

type MsgSubmitPoWResponse struct {
}

func (m *MsgSubmitPoWResponse) Reset()         { *m = MsgSubmitPoWResponse{} }
func (m *MsgSubmitPoWResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitPoWResponse) ProtoMessage()    {}
func (*MsgSubmitPoWResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eb53289cba3cd1f, []int{3}
}
func (m *MsgSubmitPoWResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitPoWResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitPoWResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitPoWResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitPoWResponse.Merge(m, src)
}
func (m *MsgSubmitPoWResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitPoWResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitPoWResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitPoWResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterValidatorPubkey)(nil), "aether.pow.v1.MsgRegisterValidatorPubkey")
	proto.RegisterType((*MsgRegisterValidatorPubkeyResponse)(nil), "aether.pow.v1.MsgRegisterValidatorPubkeyResponse")
	proto.RegisterType((*MsgSubmitPoW)(nil), "aether.pow.v1.MsgSubmitPoW")
	proto.RegisterType((*MsgSubmitPoWResponse)(nil), "aether.pow.v1.MsgSubmitPoWResponse")
}

func init() { proto.RegisterFile("aether/pow/v1/tx.proto", fileDescriptor_3eb53289cba3cd1f) }

var fileDescriptor_3eb53289cba3cd1f = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xce, 0x91, 0x36, 0x90, 0x47, 0x11, 0xc8, 0x8a, 0x52, 0xcb, 0x45, 0xa6, 0x0a, 0x1d, 0x5a,
	0x06, 0x5b, 0x81, 0x8d, 0x81, 0x81, 0x89, 0x25, 0x52, 0x65, 0x24, 0x90, 0x58, 0x22, 0xc7, 0xbd,
	0xde, 0x1d, 0xcd, 0xf9, 0x59, 0xf7, 0xce, 0x49, 0xb3, 0xb2, 0xb0, 0xf2, 0x53, 0xf8, 0x19, 0x2c,
	0x48, 0x1d, 0x11, 0x13, 0x4a, 0x06, 0xfe, 0x06, 0xf2, 0x39, 0x21, 0x89, 0x50, 0x50, 0x37, 0xbf,
	0xef, 0xfb, 0xde, 0x77, 0xdf, 0xf3, 0x7b, 0xd0, 0x4d, 0xb9, 0x95, 0xdc, 0xc4, 0x05, 0x4e, 0xe3,
	0x49, 0x3f, 0xb6, 0xd7, 0x51, 0x61, 0xd0, 0xa2, 0xf7, 0xa0, 0xc6, 0xa3, 0x02, 0xa7, 0xd1, 0xa4,
	0x1f, 0x74, 0x04, 0x0a, 0x74, 0x4c, 0x5c, 0x7d, 0xd5, 0xa2, 0xe0, 0x30, 0x43, 0xd2, 0x48, 0xb1,
	0x26, 0x51, 0x35, 0x6b, 0x12, 0x35, 0xd1, 0xfb, 0xcc, 0x20, 0x18, 0x90, 0x48, 0xb8, 0x50, 0x64,
	0xb9, 0x79, 0x97, 0x8e, 0xd5, 0x45, 0x6a, 0xd1, 0x9c, 0x97, 0xa3, 0x2b, 0x3e, 0xf3, 0x3a, 0xb0,
	0xaf, 0x55, 0xce, 0x8d, 0xcf, 0x8e, 0xd9, 0x69, 0x3b, 0xa9, 0x0b, 0xef, 0x0c, 0x1e, 0x65, 0x98,
	0x13, 0xcf, 0xa9, 0xa4, 0x61, 0xe1, 0x94, 0xfe, 0x9d, 0x63, 0x76, 0x7a, 0x90, 0x3c, 0xfc, 0x8b,
	0x2f, 0x0d, 0x1e, 0x43, 0x9b, 0x94, 0xc8, 0x53, 0x5b, 0x1a, 0xee, 0x37, 0x9d, 0x66, 0x0d, 0xbc,
	0x84, 0x4f, 0xbf, 0xbf, 0x3e, 0xab, 0x4d, 0x7b, 0x27, 0xd0, 0xdb, 0x1d, 0x24, 0xe1, 0x54, 0x54,
	0xce, 0xbd, 0x9f, 0x0c, 0x0e, 0x06, 0x24, 0xde, 0x96, 0x23, 0xad, 0xec, 0x39, 0xbe, 0xdf, 0x91,
	0xb0, 0x0b, 0x2d, 0xc9, 0x95, 0x90, 0xd6, 0xe5, 0xda, 0x4b, 0x96, 0x55, 0x15, 0xc7, 0x2a, 0xcd,
	0xc9, 0xa6, 0xba, 0x70, 0x71, 0x9a, 0xc9, 0x1a, 0xf0, 0x8e, 0xa0, 0x5d, 0x18, 0x3e, 0x19, 0xca,
	0x94, 0xa4, 0xbf, 0xe7, 0xc2, 0xde, 0xab, 0x80, 0x37, 0x29, 0x49, 0xef, 0x09, 0xdc, 0xd7, 0xdc,
	0x5c, 0x8d, 0xf9, 0xd0, 0x20, 0x5a, 0x7f, 0xdf, 0xd1, 0x50, 0x43, 0x09, 0xa2, 0xad, 0x92, 0xe4,
	0x98, 0x67, 0xdc, 0x6f, 0xb9, 0x27, 0xeb, 0xc2, 0x0b, 0x01, 0x2e, 0xd4, 0xe5, 0xa5, 0xca, 0xca,
	0xb1, 0x9d, 0xf9, 0x77, 0x1d, 0xb5, 0x81, 0x6c, 0xfd, 0x82, 0x2e, 0x74, 0x36, 0x67, 0x5b, 0x0d,
	0xfd, 0xfc, 0x3b, 0x83, 0xe6, 0x80, 0x84, 0x37, 0x80, 0xf6, 0x7a, 0xf0, 0xa3, 0x68, 0x6b, 0xf1,
	0xd1, 0x66, 0x67, 0xf0, 0xf4, 0x3f, 0xe4, 0xca, 0xd6, 0x9b, 0xc2, 0xe1, 0xae, 0xbd, 0x9f, 0xfd,
	0xdb, 0xbf, 0x43, 0x1a, 0xf4, 0x6f, 0x2d, 0x5d, 0x3d, 0xfc, 0xfa, 0xd5, 0xb7, 0x79, 0xc8, 0x6e,
	0xe6, 0x21, 0xfb, 0x35, 0x0f, 0xd9, 0x97, 0x45, 0xd8, 0xb8, 0x59, 0x84, 0x8d, 0x1f, 0x8b, 0xb0,
	0xf1, 0xe1, 0x44, 0x28, 0x2b, 0xcb, 0x51, 0x94, 0xa1, 0x8e, 0xa7, 0x12, 0x67, 0x58, 0x7e, 0x44,
	0x92, 0x2a, 0x8f, 0x97, 0xc7, 0x7f, 0x5d, 0x9d, 0xff, 0xa8, 0xe5, 0x6e, 0xf7, 0xc5, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x30, 0x63, 0xa7, 0xff, 0x13, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SubmitPoW(ctx context.Context, in *MsgSubmitPoW, opts ...grpc.CallOption) (*MsgSubmitPoWResponse, error)
	RegisterValidatorPubkey(ctx context.Context, in *MsgRegisterValidatorPubkey, opts ...grpc.CallOption) (*MsgRegisterValidatorPubkeyResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitPoW(ctx context.Context, in *MsgSubmitPoW, opts ...grpc.CallOption) (*MsgSubmitPoWResponse, error) {
	out := new(MsgSubmitPoWResponse)
	err := c.cc.Invoke(ctx, "/aether.pow.v1.Msg/SubmitPoW", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterValidatorPubkey(ctx context.Context, in *MsgRegisterValidatorPubkey, opts ...grpc.CallOption) (*MsgRegisterValidatorPubkeyResponse, error) {
	out := new(MsgRegisterValidatorPubkeyResponse)
	err := c.cc.Invoke(ctx, "/aether.pow.v1.Msg/RegisterValidatorPubkey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SubmitPoW(context.Context, *MsgSubmitPoW) (*MsgSubmitPoWResponse, error)
	RegisterValidatorPubkey(context.Context, *MsgRegisterValidatorPubkey) (*MsgRegisterValidatorPubkeyResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitPoW(ctx context.Context, req *MsgSubmitPoW) (*MsgSubmitPoWResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPoW not implemented")
}
func (*UnimplementedMsgServer) RegisterValidatorPubkey(ctx context.Context, req *MsgRegisterValidatorPubkey) (*MsgRegisterValidatorPubkeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterValidatorPubkey not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitPoW_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitPoW)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitPoW(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aether.pow.v1.Msg/SubmitPoW",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitPoW(ctx, req.(*MsgSubmitPoW))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterValidatorPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterValidatorPubkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterValidatorPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aether.pow.v1.Msg/RegisterValidatorPubkey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterValidatorPubkey(ctx, req.(*MsgRegisterValidatorPubkey))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aether.pow.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitPoW",
			Handler:    _Msg_SubmitPoW_Handler,
		},
		{
			MethodName: "RegisterValidatorPubkey",
			Handler:    _Msg_RegisterValidatorPubkey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aether/pow/v1/tx.proto",
}

func (m *MsgRegisterValidatorPubkey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterValidatorPubkey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterValidatorPubkey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConsensusPubkey) > 0 {
		i -= len(m.ConsensusPubkey)
		copy(dAtA[i:], m.ConsensusPubkey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ConsensusPubkey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Miner) > 0 {
		i -= len(m.Miner)
		copy(dAtA[i:], m.Miner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Miner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterValidatorPubkeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterValidatorPubkeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterValidatorPubkeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitPoW) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitPoW) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitPoW) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Difficulty != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Difficulty))
		i--
		dAtA[i] = 0x38
	}
	if m.Nonce != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x30
	}
	if len(m.MerkleRoot) > 0 {
		i -= len(m.MerkleRoot)
		copy(dAtA[i:], m.MerkleRoot)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MerkleRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PrevHash) > 0 {
		i -= len(m.PrevHash)
		copy(dAtA[i:], m.PrevHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PrevHash)))
		i--
		dAtA[i] = 0x22
	}
	if m.Timestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if m.Height != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Miner) > 0 {
		i -= len(m.Miner)
		copy(dAtA[i:], m.Miner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Miner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitPoWResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitPoWResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitPoWResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterValidatorPubkey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Miner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ConsensusPubkey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterValidatorPubkeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitPoW) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Miner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovTx(uint64(m.Height))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTx(uint64(m.Timestamp))
	}
	l = len(m.PrevHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MerkleRoot)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovTx(uint64(m.Nonce))
	}
	if m.Difficulty != 0 {
		n += 1 + sovTx(uint64(m.Difficulty))
	}
	return n
}

func (m *MsgSubmitPoWResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterValidatorPubkey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterValidatorPubkey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterValidatorPubkey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Miner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Miner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsensusPubkey = append(m.ConsensusPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.ConsensusPubkey == nil {
				m.ConsensusPubkey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterValidatorPubkeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterValidatorPubkeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterValidatorPubkeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitPoW) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitPoW: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitPoW: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Miner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Miner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrevHash = append(m.PrevHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PrevHash == nil {
				m.PrevHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerkleRoot = append(m.MerkleRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.MerkleRoot == nil {
				m.MerkleRoot = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Difficulty", wireType)
			}
			m.Difficulty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Difficulty |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitPoWResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitPoWResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitPoWResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
