// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aether/pow/v1/tx.proto

package pow

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterValidatorPubkey struct {
	Miner           string `protobuf:"bytes,1,opt,name=miner,proto3" json:"miner,omitempty"`
	ConsensusPubkey []byte `protobuf:"bytes,2,opt,name=consensus_pubkey,json=consensusPubkey,proto3" json:"consensus_pubkey,omitempty"`
	Signature       []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *MsgRegisterValidatorPubkey) Reset()         { *m = MsgRegisterValidatorPubkey{} }
func (m *MsgRegisterValidatorPubkey) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterValidatorPubkey) ProtoMessage()    {}
func (*MsgRegisterValidatorPubkey) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eb53289cba3cd1f, []int{0}
}
func (m *MsgRegisterValidatorPubkey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterValidatorPubkey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterValidatorPubkey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterValidatorPubkey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterValidatorPubkey.Merge(m, src)
}
func (m *MsgRegisterValidatorPubkey) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterValidatorPubkey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterValidatorPubkey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterValidatorPubkey proto.InternalMessageInfo

func (m *MsgRegisterValidatorPubkey) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *MsgRegisterValidatorPubkey) GetConsensusPubkey() []byte {
	if m != nil {
		return m.ConsensusPubkey
	}
	return nil
}

func (m *MsgRegisterValidatorPubkey) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type MsgRegisterValidatorPubkeyResponse struct {
}

func (m *MsgRegisterValidatorPubkeyResponse) Reset()         { *m = MsgRegisterValidatorPubkeyResponse{} }
func (m *MsgRegisterValidatorPubkeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterValidatorPubkeyResponse) ProtoMessage()    {}
func (*MsgRegisterValidatorPubkeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eb53289cba3cd1f, []int{1}
}
func (m *MsgRegisterValidatorPubkeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterValidatorPubkeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterValidatorPubkeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterValidatorPubkeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterValidatorPubkeyResponse.Merge(m, src)
}
func (m *MsgRegisterValidatorPubkeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterValidatorPubkeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterValidatorPubkeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterValidatorPubkeyResponse proto.InternalMessageInfo

type NativeSubmission struct {
	Height     uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp  int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PrevHash   []byte `protobuf:"bytes,3,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	MerkleRoot []byte `protobuf:"bytes,4,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	Nonce      uint64 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Difficulty uint64 `protobuf:"varint,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
}

func (m *NativeSubmission) Reset()         { *m = NativeSubmission{} }
func (m *NativeSubmission) String() string { return proto.CompactTextString(m) }
func (*NativeSubmission) ProtoMessage()    {}
func (*NativeSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eb53289cba3cd1f, []int{2}
}
func (m *NativeSubmission) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NativeSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NativeSubmission.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NativeSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NativeSubmission.Merge(m, src)
}
func (m *NativeSubmission) XXX_Size() int {
	return m.Size()
}
func (m *NativeSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_NativeSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_NativeSubmission proto.InternalMessageInfo

func (m *NativeSubmission) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *NativeSubmission) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *NativeSubmission) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *NativeSubmission) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *NativeSubmission) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *NativeSubmission) GetDifficulty() uint64 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

type MsgSubmitPoW struct {
	Miner string `protobuf:"bytes,1,opt,name=miner,proto3" json:"miner,omitempty"`
	// Types that are valid to be assigned to Submission:
	//
	//	*MsgSubmitPoW_Native
	//	*MsgSubmitPoW_AuxPow
	Submission isMsgSubmitPoW_Submission `protobuf_oneof:"submission"`
}

func (m *MsgSubmitPoW) Reset()         { *m = MsgSubmitPoW{} }
func (m *MsgSubmitPoW) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitPoW) ProtoMessage()    {}
func (*MsgSubmitPoW) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eb53289cba3cd1f, []int{3}
}
func (m *MsgSubmitPoW) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitPoW) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitPoW.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitPoW) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitPoW.Merge(m, src)
}
func (m *MsgSubmitPoW) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitPoW) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitPoW.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitPoW proto.InternalMessageInfo

type isMsgSubmitPoW_Submission interface {
	isMsgSubmitPoW_Submission()
	MarshalTo([]byte) (int, error)
	Size() int
}

type MsgSubmitPoW_Native struct {
	Native *NativeSubmission `protobuf:"bytes,2,opt,name=native,proto3,oneof" json:"native,omitempty"`
}
type MsgSubmitPoW_AuxPow struct {
	AuxPow *AuxPowData `protobuf:"bytes,3,opt,name=aux_pow,json=auxPow,proto3,oneof" json:"aux_pow,omitempty"`
}

func (*MsgSubmitPoW_Native) isMsgSubmitPoW_Submission() {}
func (*MsgSubmitPoW_AuxPow) isMsgSubmitPoW_Submission() {}

func (m *MsgSubmitPoW) GetSubmission() isMsgSubmitPoW_Submission {
	if m != nil {
		return m.Submission
	}
	return nil
}

func (m *MsgSubmitPoW) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *MsgSubmitPoW) GetNative() *NativeSubmission {
	if x, ok := m.GetSubmission().(*MsgSubmitPoW_Native); ok {
		return x.Native
	}
	return nil
}

func (m *MsgSubmitPoW) GetAuxPow() *AuxPowData {
	if x, ok := m.GetSubmission().(*MsgSubmitPoW_AuxPow); ok {
		return x.AuxPow
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MsgSubmitPoW) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MsgSubmitPoW_Native)(nil),
		(*MsgSubmitPoW_AuxPow)(nil),
	}
}

type MsgSubmitPoWResponse struct {
}

func (m *MsgSubmitPoWResponse) Reset()         { *m = MsgSubmitPoWResponse{} }
func (m *MsgSubmitPoWResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitPoWResponse) ProtoMessage()    {}
func (*MsgSubmitPoWResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eb53289cba3cd1f, []int{4}
}
func (m *MsgSubmitPoWResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitPoWResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitPoWResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitPoWResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitPoWResponse.Merge(m, src)
}
func (m *MsgSubmitPoWResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitPoWResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitPoWResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitPoWResponse proto.InternalMessageInfo

// MsgUpdateParams is x/pow's authority-gated params-update message,
// meant to be executed only via x/governance's generic
// MsgSubmitParamChangeProposal path (see that message's own proto
// comment) -- never signed directly by a real user, since `authority`
// must equal the governance module account, which has no private key.
//
// Deliberately scoped to the operational tuning knobs only:
// EpochLength, TopKSize, BondCooldown, RecencyWindowK, and
// BeaconRoundsPerBlock. TargetBlockTime, MinDifficulty, MaxDifficulty,
// and Difficulty are intentionally excluded -- they interact directly
// with mining economics and the reward decay schedule
// (ComputeScheduledBlockReward derives blocksPerYear from
// TargetBlockTime), and deserve their own dedicated design pass before
// being governance-adjustable, not a casual inclusion here.
// InitialDifficulty is excluded because it has no live keeper storage
// at all (see QueryParamsResponse's comment) -- there is nothing for
// this message to update. BlockReward is excluded because it now
// defaults to a computed decay curve rather than a governance-set
// value (see the same comment). TailEmission, a similarly inert field,
// was removed from Params entirely rather than merely excluded here --
// see its removal note in x/pow/types.go.
//
// This is a full-replace message, matching x/consensus's own
// MsgUpdateParams convention in this codebase: submit ALL five fields
// with their intended final values, not just the one being changed.
// The CLI command fetches current live values first specifically so
// callers don't have to hand-assemble the other four from memory.
type MsgUpdateParams struct {
	Authority            string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	EpochLength          int64  `protobuf:"varint,2,opt,name=epoch_length,json=epochLength,proto3" json:"epoch_length,omitempty"`
	TopKSize             int64  `protobuf:"varint,3,opt,name=top_k_size,json=topKSize,proto3" json:"top_k_size,omitempty"`
	BondCooldown         int64  `protobuf:"varint,4,opt,name=bond_cooldown,json=bondCooldown,proto3" json:"bond_cooldown,omitempty"`
	RecencyWindowK       int64  `protobuf:"varint,5,opt,name=recency_window_k,json=recencyWindowK,proto3" json:"recency_window_k,omitempty"`
	BeaconRoundsPerBlock int64  `protobuf:"varint,6,opt,name=beacon_rounds_per_block,json=beaconRoundsPerBlock,proto3" json:"beacon_rounds_per_block,omitempty"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eb53289cba3cd1f, []int{5}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetEpochLength() int64 {
	if m != nil {
		return m.EpochLength
	}
	return 0
}

func (m *MsgUpdateParams) GetTopKSize() int64 {
	if m != nil {
		return m.TopKSize
	}
	return 0
}

func (m *MsgUpdateParams) GetBondCooldown() int64 {
	if m != nil {
		return m.BondCooldown
	}
	return 0
}

func (m *MsgUpdateParams) GetRecencyWindowK() int64 {
	if m != nil {
		return m.RecencyWindowK
	}
	return 0
}

func (m *MsgUpdateParams) GetBeaconRoundsPerBlock() int64 {
	if m != nil {
		return m.BeaconRoundsPerBlock
	}
	return 0
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eb53289cba3cd1f, []int{6}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterValidatorPubkey)(nil), "aether.pow.v1.MsgRegisterValidatorPubkey")
	proto.RegisterType((*MsgRegisterValidatorPubkeyResponse)(nil), "aether.pow.v1.MsgRegisterValidatorPubkeyResponse")
	proto.RegisterType((*NativeSubmission)(nil), "aether.pow.v1.NativeSubmission")
	proto.RegisterType((*MsgSubmitPoW)(nil), "aether.pow.v1.MsgSubmitPoW")
	proto.RegisterType((*MsgSubmitPoWResponse)(nil), "aether.pow.v1.MsgSubmitPoWResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "aether.pow.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "aether.pow.v1.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("aether/pow/v1/tx.proto", fileDescriptor_3eb53289cba3cd1f) }

var fileDescriptor_3eb53289cba3cd1f = []byte{
	// 708 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x4f, 0xdb, 0x4a,
	0x14, 0x8d, 0x09, 0xe4, 0x91, 0x9b, 0xf0, 0x21, 0x2b, 0x22, 0x21, 0x20, 0xc3, 0x0b, 0xe8, 0x09,
	0xde, 0x22, 0x11, 0xbc, 0xd7, 0x45, 0x59, 0x54, 0x2a, 0xed, 0x02, 0x89, 0xa6, 0x8a, 0x8c, 0x0a,
	0x52, 0x37, 0xd6, 0xc4, 0x19, 0xec, 0x69, 0xe2, 0xb9, 0x96, 0x67, 0x1c, 0x27, 0x2c, 0xbb, 0x68,
	0xb7, 0xfd, 0x13, 0x5d, 0xb7, 0x3f, 0xa0, 0x3f, 0xa0, 0x4b, 0x96, 0x5d, 0x56, 0xb0, 0xe8, 0xdf,
	0xa8, 0x3c, 0x36, 0x49, 0x08, 0x0a, 0xea, 0x2e, 0x73, 0xce, 0xbd, 0x67, 0xee, 0x3d, 0xc7, 0x19,
	0x58, 0x23, 0x54, 0xba, 0x34, 0x68, 0xf8, 0x18, 0x35, 0xfa, 0x07, 0x0d, 0x39, 0xa8, 0xfb, 0x01,
	0x4a, 0xd4, 0x97, 0x12, 0xbc, 0xee, 0x63, 0x54, 0xef, 0x1f, 0x54, 0x4b, 0x0e, 0x3a, 0xa8, 0x98,
	0x46, 0xfc, 0x2b, 0x29, 0xaa, 0x96, 0x6d, 0x14, 0x1e, 0x8a, 0x86, 0x27, 0x9c, 0xb8, 0xd9, 0x13,
	0x4e, 0x4a, 0x54, 0xef, 0xab, 0x92, 0x70, 0x10, 0xeb, 0x28, 0xae, 0xf6, 0x51, 0x83, 0x6a, 0x53,
	0x38, 0x26, 0x75, 0x98, 0x90, 0x34, 0x38, 0x27, 0x3d, 0xd6, 0x21, 0x12, 0x83, 0x56, 0xd8, 0xee,
	0xd2, 0xa1, 0x5e, 0x82, 0x05, 0x8f, 0x71, 0x1a, 0x54, 0xb4, 0x6d, 0x6d, 0x2f, 0x6f, 0x26, 0x07,
	0x7d, 0x1f, 0x56, 0x6d, 0xe4, 0x82, 0x72, 0x11, 0x0a, 0xcb, 0x57, 0x95, 0x95, 0xb9, 0x6d, 0x6d,
	0xaf, 0x68, 0xae, 0x8c, 0xf0, 0x54, 0x60, 0x13, 0xf2, 0x82, 0x39, 0x9c, 0xc8, 0x30, 0xa0, 0x95,
	0xac, 0xaa, 0x19, 0x03, 0x47, 0xf0, 0xfe, 0xd7, 0xd7, 0x7f, 0x13, 0xd1, 0xda, 0x2e, 0xd4, 0x66,
	0x0f, 0x62, 0x52, 0xe1, 0xc7, 0xca, 0xb5, 0x6f, 0x1a, 0xac, 0xbe, 0x26, 0x92, 0xf5, 0xe9, 0x59,
	0xd8, 0xf6, 0x98, 0x10, 0x0c, 0xb9, 0xbe, 0x06, 0x39, 0x97, 0x32, 0xc7, 0x95, 0x6a, 0xcc, 0x79,
	0x33, 0x3d, 0xc5, 0x97, 0x4b, 0xe6, 0x51, 0x21, 0x89, 0xe7, 0xab, 0x01, 0xb3, 0xe6, 0x18, 0xd0,
	0x37, 0x20, 0xef, 0x07, 0xb4, 0x6f, 0xb9, 0x44, 0xb8, 0xe9, 0x68, 0x8b, 0x31, 0x70, 0x42, 0x84,
	0xab, 0x6f, 0x41, 0xc1, 0xa3, 0x41, 0xb7, 0x47, 0xad, 0x00, 0x51, 0x56, 0xe6, 0x15, 0x0d, 0x09,
	0x64, 0x22, 0xca, 0xd8, 0x19, 0x8e, 0xdc, 0xa6, 0x95, 0x05, 0x75, 0x65, 0x72, 0xd0, 0x0d, 0x80,
	0x0e, 0xbb, 0xbc, 0x64, 0x76, 0xd8, 0x93, 0xc3, 0x4a, 0x4e, 0x51, 0x13, 0x48, 0xed, 0x8b, 0x06,
	0xc5, 0xa6, 0x70, 0xd4, 0xec, 0xb2, 0x85, 0x17, 0x33, 0x0c, 0x7e, 0x0a, 0x39, 0xae, 0x96, 0x54,
	0x53, 0x17, 0x0e, 0xb7, 0xea, 0xf7, 0x3e, 0x80, 0xfa, 0xb4, 0x03, 0x27, 0x19, 0x33, 0x6d, 0xd0,
	0xff, 0x87, 0xbf, 0x48, 0x38, 0xb0, 0x7c, 0x8c, 0xd4, 0x4e, 0x85, 0xc3, 0xf5, 0xa9, 0xde, 0xe7,
	0xe1, 0xa0, 0x85, 0xd1, 0x4b, 0x22, 0x49, 0xdc, 0x45, 0xd4, 0x69, 0x32, 0x88, 0xe3, 0x22, 0x80,
	0x18, 0x29, 0xd7, 0xd6, 0xa0, 0x34, 0x39, 0xf0, 0x28, 0x88, 0x0f, 0x73, 0xb0, 0xd2, 0x14, 0xce,
	0x1b, 0xbf, 0x43, 0x24, 0x6d, 0x91, 0x80, 0x78, 0x22, 0xf6, 0x9b, 0x84, 0xd2, 0xc5, 0x80, 0xc9,
	0x61, 0xba, 0xd0, 0x18, 0xd0, 0xff, 0x86, 0x22, 0xf5, 0xd1, 0x76, 0xad, 0x1e, 0xe5, 0x8e, 0x74,
	0xd3, 0x40, 0x0a, 0x0a, 0x7b, 0xa5, 0x20, 0x7d, 0x13, 0x40, 0xa2, 0x6f, 0x75, 0x2d, 0xc1, 0xae,
	0x92, 0xcf, 0x25, 0x6b, 0x2e, 0x4a, 0xf4, 0x4f, 0xcf, 0xd8, 0x15, 0xd5, 0x77, 0x60, 0xa9, 0x8d,
	0xbc, 0x63, 0xd9, 0x88, 0xbd, 0x0e, 0x46, 0x5c, 0xa5, 0x92, 0x35, 0x8b, 0x31, 0xf8, 0x22, 0xc5,
	0xf4, 0x3d, 0x58, 0x0d, 0xa8, 0x4d, 0xb9, 0x3d, 0xb4, 0x22, 0xc6, 0x3b, 0x18, 0x59, 0x5d, 0x15,
	0x51, 0xd6, 0x5c, 0x4e, 0xf1, 0x0b, 0x05, 0x9f, 0xea, 0x4f, 0xa0, 0xdc, 0xa6, 0xc4, 0x46, 0x6e,
	0x05, 0x18, 0xf2, 0x8e, 0xb0, 0x7c, 0x1a, 0x58, 0xed, 0x1e, 0xda, 0x5d, 0x15, 0x5c, 0xd6, 0x2c,
	0x25, 0xb4, 0xa9, 0xd8, 0x16, 0x0d, 0x8e, 0x63, 0xee, 0x68, 0x39, 0xb6, 0x6a, 0xbc, 0x56, 0x6d,
	0x1d, 0xca, 0x53, 0x3e, 0xdc, 0x79, 0x74, 0xf8, 0x79, 0x0e, 0xb2, 0x4d, 0xe1, 0xe8, 0x4d, 0xc8,
	0x8f, 0x13, 0xdf, 0x98, 0xca, 0x63, 0xd2, 0xdd, 0xea, 0xce, 0x23, 0xe4, 0x9d, 0xac, 0x1e, 0x41,
	0x79, 0xd6, 0xff, 0x75, 0xff, 0x61, 0xff, 0x8c, 0xd2, 0xea, 0xc1, 0x1f, 0x97, 0x8e, 0x2e, 0x3e,
	0x87, 0xe2, 0xbd, 0xbc, 0x8d, 0x87, 0x12, 0x93, 0x7c, 0xf5, 0x9f, 0xc7, 0xf9, 0x3b, 0xdd, 0xe3,
	0x67, 0xdf, 0x6f, 0x0c, 0xed, 0xfa, 0xc6, 0xd0, 0x7e, 0xde, 0x18, 0xda, 0xa7, 0x5b, 0x23, 0x73,
	0x7d, 0x6b, 0x64, 0x7e, 0xdc, 0x1a, 0x99, 0xb7, 0xbb, 0x0e, 0x93, 0x6e, 0xd8, 0xae, 0xdb, 0xe8,
	0x35, 0x22, 0x17, 0x87, 0x18, 0xbe, 0x43, 0xe1, 0x32, 0xde, 0x48, 0x9f, 0xb4, 0x41, 0xfc, 0xa8,
	0xb5, 0x73, 0xea, 0x2d, 0xfb, 0xef, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x5f, 0x62, 0x66,
	0x3f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SubmitPoW(ctx context.Context, in *MsgSubmitPoW, opts ...grpc.CallOption) (*MsgSubmitPoWResponse, error)
	RegisterValidatorPubkey(ctx context.Context, in *MsgRegisterValidatorPubkey, opts ...grpc.CallOption) (*MsgRegisterValidatorPubkeyResponse, error)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitPoW(ctx context.Context, in *MsgSubmitPoW, opts ...grpc.CallOption) (*MsgSubmitPoWResponse, error) {
	out := new(MsgSubmitPoWResponse)
	err := c.cc.Invoke(ctx, "/aether.pow.v1.Msg/SubmitPoW", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterValidatorPubkey(ctx context.Context, in *MsgRegisterValidatorPubkey, opts ...grpc.CallOption) (*MsgRegisterValidatorPubkeyResponse, error) {
	out := new(MsgRegisterValidatorPubkeyResponse)
	err := c.cc.Invoke(ctx, "/aether.pow.v1.Msg/RegisterValidatorPubkey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/aether.pow.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SubmitPoW(context.Context, *MsgSubmitPoW) (*MsgSubmitPoWResponse, error)
	RegisterValidatorPubkey(context.Context, *MsgRegisterValidatorPubkey) (*MsgRegisterValidatorPubkeyResponse, error)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitPoW(ctx context.Context, req *MsgSubmitPoW) (*MsgSubmitPoWResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPoW not implemented")
}
func (*UnimplementedMsgServer) RegisterValidatorPubkey(ctx context.Context, req *MsgRegisterValidatorPubkey) (*MsgRegisterValidatorPubkeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterValidatorPubkey not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitPoW_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitPoW)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitPoW(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aether.pow.v1.Msg/SubmitPoW",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitPoW(ctx, req.(*MsgSubmitPoW))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterValidatorPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterValidatorPubkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterValidatorPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aether.pow.v1.Msg/RegisterValidatorPubkey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterValidatorPubkey(ctx, req.(*MsgRegisterValidatorPubkey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aether.pow.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aether.pow.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitPoW",
			Handler:    _Msg_SubmitPoW_Handler,
		},
		{
			MethodName: "RegisterValidatorPubkey",
			Handler:    _Msg_RegisterValidatorPubkey_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aether/pow/v1/tx.proto",
}

func (m *MsgRegisterValidatorPubkey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterValidatorPubkey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterValidatorPubkey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConsensusPubkey) > 0 {
		i -= len(m.ConsensusPubkey)
		copy(dAtA[i:], m.ConsensusPubkey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ConsensusPubkey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Miner) > 0 {
		i -= len(m.Miner)
		copy(dAtA[i:], m.Miner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Miner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterValidatorPubkeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterValidatorPubkeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterValidatorPubkeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *NativeSubmission) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NativeSubmission) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NativeSubmission) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Difficulty != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Difficulty))
		i--
		dAtA[i] = 0x30
	}
	if m.Nonce != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x28
	}
	if len(m.MerkleRoot) > 0 {
		i -= len(m.MerkleRoot)
		copy(dAtA[i:], m.MerkleRoot)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MerkleRoot)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PrevHash) > 0 {
		i -= len(m.PrevHash)
		copy(dAtA[i:], m.PrevHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PrevHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Timestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x10
	}
	if m.Height != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitPoW) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitPoW) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitPoW) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Submission != nil {
		{
			size := m.Submission.Size()
			i -= size
			if _, err := m.Submission.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.Miner) > 0 {
		i -= len(m.Miner)
		copy(dAtA[i:], m.Miner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Miner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitPoW_Native) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitPoW_Native) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Native != nil {
		{
			size, err := m.Native.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *MsgSubmitPoW_AuxPow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitPoW_AuxPow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.AuxPow != nil {
		{
			size, err := m.AuxPow.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *MsgSubmitPoWResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitPoWResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitPoWResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BeaconRoundsPerBlock != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BeaconRoundsPerBlock))
		i--
		dAtA[i] = 0x30
	}
	if m.RecencyWindowK != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RecencyWindowK))
		i--
		dAtA[i] = 0x28
	}
	if m.BondCooldown != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BondCooldown))
		i--
		dAtA[i] = 0x20
	}
	if m.TopKSize != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TopKSize))
		i--
		dAtA[i] = 0x18
	}
	if m.EpochLength != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EpochLength))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterValidatorPubkey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Miner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ConsensusPubkey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterValidatorPubkeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *NativeSubmission) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovTx(uint64(m.Height))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTx(uint64(m.Timestamp))
	}
	l = len(m.PrevHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MerkleRoot)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovTx(uint64(m.Nonce))
	}
	if m.Difficulty != 0 {
		n += 1 + sovTx(uint64(m.Difficulty))
	}
	return n
}

func (m *MsgSubmitPoW) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Miner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Submission != nil {
		n += m.Submission.Size()
	}
	return n
}

func (m *MsgSubmitPoW_Native) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Native != nil {
		l = m.Native.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}
func (m *MsgSubmitPoW_AuxPow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AuxPow != nil {
		l = m.AuxPow.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}
func (m *MsgSubmitPoWResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EpochLength != 0 {
		n += 1 + sovTx(uint64(m.EpochLength))
	}
	if m.TopKSize != 0 {
		n += 1 + sovTx(uint64(m.TopKSize))
	}
	if m.BondCooldown != 0 {
		n += 1 + sovTx(uint64(m.BondCooldown))
	}
	if m.RecencyWindowK != 0 {
		n += 1 + sovTx(uint64(m.RecencyWindowK))
	}
	if m.BeaconRoundsPerBlock != 0 {
		n += 1 + sovTx(uint64(m.BeaconRoundsPerBlock))
	}
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterValidatorPubkey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterValidatorPubkey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterValidatorPubkey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Miner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Miner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsensusPubkey = append(m.ConsensusPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.ConsensusPubkey == nil {
				m.ConsensusPubkey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterValidatorPubkeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterValidatorPubkeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterValidatorPubkeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NativeSubmission) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NativeSubmission: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NativeSubmission: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrevHash = append(m.PrevHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PrevHash == nil {
				m.PrevHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerkleRoot = append(m.MerkleRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.MerkleRoot == nil {
				m.MerkleRoot = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Difficulty", wireType)
			}
			m.Difficulty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Difficulty |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitPoW) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitPoW: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitPoW: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Miner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Miner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Native", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NativeSubmission{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Submission = &MsgSubmitPoW_Native{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuxPow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AuxPowData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Submission = &MsgSubmitPoW_AuxPow{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitPoWResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitPoWResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitPoWResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLength", wireType)
			}
			m.EpochLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochLength |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopKSize", wireType)
			}
			m.TopKSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TopKSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondCooldown", wireType)
			}
			m.BondCooldown = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BondCooldown |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecencyWindowK", wireType)
			}
			m.RecencyWindowK = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecencyWindowK |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconRoundsPerBlock", wireType)
			}
			m.BeaconRoundsPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeaconRoundsPerBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
